import torch

class EmbeddingLoader:
    """
    Utility class to load and validate precomputed protein embeddings.
    
    This class loads embeddings generated by ESM-2 (or similar models) from .pt files
    and validates them against a DataFrame containing protein structure information.
    
    Args:
        embedding_path (str): Path to the .pt file containing precomputed embeddings.
                             Expected format: {"sequence": [...], "embeddings": tensor}
    
    Attributes:
        embedding_path (str): Stored path to the embedding file.
    
    Example:
        >>> loader = EmbeddingLoader("data/embeddings/P12345_embedding.pt")
        >>> embeddings = loader.load(protein_df)
        >>> print(embeddings.shape)  # [num_residues, embedding_dim]
    """

    def __init__(self, embedding_path):
        """
        Initialize the EmbeddingLoader with a file path.
        
        Args:
            embedding_path (str): Path to .pt file containing embeddings.
        """
        self.embedding_path = embedding_path

    def load(self, df, key="embeddings"):
        """
        Load embeddings from file and validate against DataFrame structure.
        
        Performs two critical validations:
        1. Length validation: Ensures embedding count matches DataFrame rows
        2. Sequence validation: Checks if embedding sequence matches PDB sequence
        
        Args:
            df (pd.DataFrame): DataFrame with protein structure information.
                              Must contain 'residue_name' column with single-letter amino acids.
            key (str, optional): Dictionary key for embeddings in .pt file. 
                                Defaults to "embeddings".
        
        Returns:
            torch.Tensor: Loaded embeddings as float tensor, shape [num_residues, embedding_dim].
        
        Raises:
            ValueError: If embedding dimensions don't match DataFrame length.
        
        Warning:
            Prints warning if sequences don't match exactly (may indicate alignment issues).
        """
        # Load embedding file (contains sequence and embeddings)
        data = torch.load(self.embedding_path, weights_only=True)
        loaded_sequence = data["sequence"]       # List of amino acids from embedding
        loaded_embeddings = data[key]            # Tensor: [seq_length, embedding_dim]
        
        # Extract sequence from DataFrame (from PDB structure)
        pdb_sequence = ''.join(df['residue_name'].tolist())

        # Validation 1: Check dimension compatibility
        # Ensures each residue in DataFrame has a corresponding embedding
        if loaded_embeddings.shape[0] != len(df):
            raise ValueError(
                f"Embedding size mismatch: "
                f"{loaded_embeddings.shape[0]} embeddings vs {len(df)} residues in DataFrame"
            )

        # Validation 2: Check sequence identity
        # Compares PDB sequence (from structure) with embedding sequence (from FASTA)
        # Mismatches may occur due to missing residues, mutations, or preprocessing differences
        if len(pdb_sequence) != len(loaded_sequence) or pdb_sequence != "".join(loaded_sequence).upper():
            print(
                f"⚠ WARNING: PDB sequence and loaded embedding sequence do not match exactly.\n"
                f"  PDB length: {len(pdb_sequence)}, Embedding length: {len(loaded_sequence)}"
            )
        else:
            print(
                f"✓ Embedding sequence matches PDB sequence. "
                f"({len(pdb_sequence)} residues, {len(loaded_sequence)} embeddings)"
            )

        # Return embeddings as float32 tensor (required for most PyTorch operations)
        return loaded_embeddings.float()